name: Api call
description: Makes an api call and checks the response status code
inputs:
  url:
    description: "The url to call"
    required: true
  statusCode:
    description: "The expected status code of the response"
    default: "200"
  enabled:
    description: "Allow the api to run. This is used to determine if the job should run or not"
    required: true
  authHeader:
    description: "The optional authentication header name to use for supplying the auth value"
    default: ""
  method:
    description: "The method to use for the api call"
    default: "GET"

runs:
  using: 'composite'
  steps:
    - name: Calling api
      env:
        HTTP_METHOD: ${{ inputs.method }}
        TARGET_URL: ${{ inputs.url }}
        EXPECTED_STATUS_CODE: ${{ inputs.statusCode }}
        AUTH_HEADER_NAME: ${{ inputs.authHeader }}
        AUTH_HEADER_VALUE: ${{ env.AUTH_VALUE }}
      run: |
          set -euo pipefail

          echo '===================== Calling api ========================'
          echo "$HTTP_METHOD $TARGET_URL"
          echo '========================================================='

          max_retries=5
          retry_count=0
          expected_status_code="$EXPECTED_STATUS_CODE"

          while [ $retry_count -lt $max_retries ]; do

              if [ -n "$AUTH_HEADER_NAME" ] && [ -n "$AUTH_HEADER_VALUE" ]; then
                rs=$(curl -X "$HTTP_METHOD" -H "$AUTH_HEADER_NAME: $AUTH_HEADER_VALUE" --write-out '%{http_code}' --silent -m 30 --output /dev/null "$TARGET_URL")
              else
                rs=$(curl -X "$HTTP_METHOD" --write-out '%{http_code}' --silent -m 30 --output /dev/null "$TARGET_URL")
              fi

              if [ $rs -eq $expected_status_code ]; then
                echo "Api call was successful with status code $rs"
                exit 0
              else
                echo "Api call failed with status code $rs. Retrying..."
              retry_count=$((retry_count + 1))
                sleep 2 # Wait for 2 seconds before retrying
              fi
          done

          if [ $retry_count -eq $max_retries ]; then
              echo "Request failed after $max_retries retries. Exiting."
          fi

          exit -1
      shell: bash

