name: Cypress Runner
description: |
  Runs Cypress tests in a GitHub Actions workflow. This workflow is designed to be reusable and can be called from other workflows.
  It installs the necessary dependencies, runs linting, executes the Cypress tests, and uploads the test results, screenshots, and videos as artifacts.
on:
  workflow_call:
    inputs:
      environment_name:
        description: ""
        required: true
        type: string
      base_url:
        description: ""
        required: true
        type: string
      working_directory:
        description: ""
        required: true
        type: string
      allow_run:
        description: ""
        type: boolean
        required: true
      command_line_args:
        description: "Command line arguments to pass to cypress"
        required: false
        type: string
        default: ""
    secrets:
      cypressUserPassword:
        description: "The cypress use password"
        required: false
      cypressApiKey:
        description: "The apu key that the cypress run can use to call an external api"
        required: false

  workflow_dispatch:

jobs:
  cypress_run:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yarn
        working-directory: ${{ inputs.working_directory }}
        run: |
          npm install -g yarn

      - name: Yarn install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: |
          yarn install

      - name: Lint
        working-directory: ${{ inputs.working_directory }}
        run: |
          yarn lint

      - name: Cypress run
        id: cypress_run
        if: ${{ inputs.allow_run }}
        working-directory: ${{ inputs.working_directory }}
        env:
          CYPRESS_cypressUserPassword: '${{ secrets.PRD_CYPRESS_USER_PASSWORD }}'
          CYPRESS_cypressApiKey: '${{ secrets.PRD_CYPRESS_API_KEY }}'
        run: |
          yarn cypress run --config baseUrl=${{ inputs.base_url }}  ${{ inputs.command_line_args }}
        continue-on-error: true

      - name: Upload test results
        if: ${{ inputs.allow_run }}
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.environment_name }}.cypress-test-results
            path: ${{ inputs.working_directory }}/results/
            include-hidden-files: true

      - name: Upload screenshots
        if: ${{ inputs.allow_run }}
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.environment_name }}.cypress-screenshots
            path: ${{ inputs.working_directory }}/cypress/screenshots/
            include-hidden-files: true

      - name: Upload videos
        if: ${{ inputs.allow_run }}
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.environment_name }}.cypress-videos
            path: ${{ inputs.working_directory }}/cypress/videos/
            include-hidden-files: true

      - name: Check cypress run outcome
        if: steps.cypress_run.outcome == 'failure'
        run: exit 1