name: Golang Api Build

description: |
    This workflow builds dotnet api applications. It installs dependencies, runs tests, builds the application and uploads the build artifact.
    This workflow is designed to be reusable and can be called from other workflows.
on:
  workflow_call:
    inputs:
        go_version:
            description: "The version of Go to use"
            required: true
            type: string
            default: "1.24.2"

        go_mod_directory:
            description: "The sub directory of the source code to build"
            required: true
            type: string

        artifact_name:
            description: "The name of the artifact to upload"
            required: true
            type: string
            default: "dotnet-build-artifact"

  workflow_dispatch:


jobs:
  build:
    name: Build and test app
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version: ${{ inputs.go_version }}
            cache-dependency-path: ${{ inputs.go_mod_directory }}/go.sum

      - name: Go version
        run: go version

      - name: Install dependencies
        run: go mod download
        working-directory: ${{ inputs.go_mod_directory }}

      - name: Create build output directory
        run: mkdir -p dist

      - name: Clean build output directory
        run: rm -r dist

      - name: Build app
        run: CGO_ENABLED=0 GOOS=linux go build -o dist ${{ inputs.go_mod_directory }}/cmd
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist
          include-hidden-files: true
          if-no-files-found: error
