name: UI Storybook Build
description: |
    This workflow builds the UI Storybook documentation for a component library. It installs dependencies, runs linting, tests, builds the application and uploads the build artifact.
    This workflow is designed to be reusable and can be called from other workflows.
on:
  workflow_call:
    inputs:
      working_directory:
        description: ""
        required: true
        type: string
      node_version:
        description: "The node version to use"
        required: false
        default: "23.5.x"
        type: string
      artifact_name:
        description: "The name of the artifact to upload"
        required: false
        type: string
        default: "ui-build-artifact"
      upload_artifact:
        description: "Whether to upload the artifact or not"
        required: true
        type: boolean


  workflow_dispatch:

jobs:
  build:
    name: Build and test app
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ inputs.node_version }}'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install
        working-directory: ${{ inputs.working_directory }}
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: ${{ inputs.working_directory }}
        run: yarn build-storybook-docs

      - name: Prepare artifact
        working-directory: ${{ inputs.working_directory }}
        run: |
          # Create an artifact directory and new copy of the dist folder
          mkdir -p artifact/
          mkdir -p artifact/storybook-static
          cp -r storybook-static/. artifact/storybook-static/
          
          echo "Files copied to artifact directory including distribution and setup files"
          echo "------------------------------------------------------------------"
          cd artifact
          ls -R

      - name: Upload artifact
        if: ${{ inputs.upload_artifact == true }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.working_directory }}/artifact
          include-hidden-files: true
          if-no-files-found: error